### ISSUE TITLE
Add Docker Support for Python Code Execution

### ISSUE THREAD

**Issue by kartik-212004** [thelegendev/Cipherion#1]
We need to add Docker support to our project to ensure consistent Python code execution across different environments.

**Comment by diptodeepb** [comment]
Hi @kartik-212004 ,
While I do appreciate you willing to make an effort, I'd have to reject this idea here.

I strongly believe that this project doesn't need containerization via a Dockerfile at the moment, considering the project's relative simplicity to even consider one. It would turn out to be an unnecessary hassle for users, given its relative complexity.
