### ISSUE TITLE
Add Variety of Encryption Methods

### ISSUE THREAD

**Issue by pokymono** [thelegendev/Cipherion#2]
I would like to propose a feature that adds support for multiple encryption algorithms in Cipherion. Currently, the project exclusively uses AES encryption. By implementing additional encryption methods, we can enhance the flexibility and security options available to users.

**Comment by diptodeepb** [comment]
Hi @Rishitshivam ,
This idea sounds good to me, I'm assigning this issue to you. 👍

**Comment by diptodeepb** [comment]
Closing this issue as it is related to PR #7 , which has been merged.
