### ISSUE TITLE
make welcome page more responsive

### ISSUE THREAD

**Issue by RishiAnand108** [thelegendev/Cipherion#3]
This updated script makes the separator line as wide as the terminal, enhancing the responsiveness of the display. The shutil.get_terminal_size().columns line dynamically adjusts the width of the separator to fit the terminal size. Happy coding with Cipherion! as doing these will make the page more responsive and imrpove the user experience.
please assign me this task.

**Comment by RishiAnand108** [comment]
import pyfiglet
import shutil

def welcome():
    # Get the terminal width to make the separator dynamic
    terminal_width = shutil.get_terminal_size().columns
    sep = "-" * terminal_width
    
    welcmsg = pyfiglet.figlet_format("Cipherion")
    
    print(sep)
    print(welcmsg)
    print(sep)
    print("Welcome to Cipherion!")
    print("A robust tool for encrypting and securely storing sensitive information.")
    print(sep)

# Call the welcome function
welcome()
 these is the change i have to put in these .

**Comment by RishiAnand108** [comment]
Sir please accept my pr and merge it.

**Comment by diptodeepb** [comment]
@RishiAnand108 Make the necessary changes in the PR, and I'll.

**Comment by RishiAnand108** [comment]
Which changes sir can you tell please

**Comment by diptodeepb** [comment]
Check the PR, I've mentioned there already.

**Comment by RishiAnand108** [comment]
sir can you please merge my PR

**Comment by diptodeepb** [comment]
Closing this issue since #4 was closed by contributor and marked as incomplete.
